In [1]:
import numpy as np
import pandas as pd
import json

In [46]:
vote_data_year = {}
vote_data_by_year = json.loads(open("senatevotedata.json").read())
#vote_data = pd.read_
vote_yes = {}
for year in range(1989, 2014):
    vote_data_year[year] = list(pd.DataFrame(vote_data_by_year["year"][str(year)])['votes'])
    vote_data_year[year] = [bill['Yea'] for bill in vote_data_year[year]]
    #list of lists, each list is group of people who voted for the same bill
    df = pd.Series()
    bill_number = 0
    for bill in vote_data_year[year]:
        for person in bill:
            df = pd.concat([df,pd.Series(person).append(pd.Series([bill_number], index = ['bill_number']))], axis = 1)
        bill_number += 1
    df = df.transpose()
    df.ix[1:]
    vote_yes[year] = df

In [ ]:
#don't run this 
for i in range(1989, 2014):
    vote_yes[i]= vote_yes[i].ix[1:]

In [66]:
for i in range(1989, 2014):
    print vote_yes[i].head()

  bill_number      display_name first_name    id  last_name party state
1           0      Adams (D-WA)      Brock  S180      Adams     D    WA
2           0  Armstrong (R-CO)    William  S134  Armstrong     R    CO
3           0     Baucus (D-MT)        Max  S127     Baucus     D    MT
4           0    Bentsen (D-TX)      Lloyd  S009    Bentsen     D    TX
5           0      Biden (D-DE)     Joseph  S010      Biden     D    DE
  bill_number      display_name first_name    id  last_name party state
1           0      Adams (D-WA)      Brock  S180      Adams     D    WA
2           0  Armstrong (R-CO)    William  S134  Armstrong     R    CO
3           0     Baucus (D-MT)        Max  S127     Baucus     D    MT
4           0    Bentsen (D-TX)      Lloyd  S009    Bentsen     D    TX
5           0      Biden (D-DE)     Joseph  S010      Biden     D    DE
  bill_number    display_name first_name    id last_name party state
1           0    Adams (D-WA)      Brock  S180     Adams     D    WA
2           0    Akaka (D-HI)     Daniel  S213     Akaka     D    HI
3           0   Baucus (D-MT)        Max  S127    Baucus     D    MT
4           0  Bentsen (D-TX)      Lloyd  S009   Bentsen     D    TX
5           0    Biden (D-DE)     Joseph  S010     Biden     D    DE
  bill_number     display_name first_name    id last_name party state
1           0     Adams (D-WA)      Brock  S180     Adams     D    WA
2           0     Akaka (D-HI)     Daniel  S213     Akaka     D    HI
3           0    Baucus (D-MT)        Max  S127    Baucus     D    MT
4           0     Biden (D-DE)     Joseph  S010     Biden     D    DE
5           0  Bingaman (D-NM)       Jeff  S167  Bingaman     D    NM
     0 bill_number     display_name   first_name    id last_name party state
1  NaN           0     Akaka (D-HI)       Daniel  S213     Akaka     D    HI
2  NaN           0    Baucus (D-MT)          Max  S127    Baucus     D    MT
3  NaN           0     Biden (D-DE)       Joseph  S010     Biden     D    DE
4  NaN           0  Bingaman (D-NM)         Jeff  S167  Bingaman     D    NM
5  NaN           0      Bond (R-MO)  Christopher  S200      Bond     R    MO
     0 bill_number     display_name first_name    id last_name party state
1  NaN           0     Akaka (D-HI)     Daniel  S213     Akaka     D    HI
2  NaN           0    Baucus (D-MT)        Max  S127    Baucus     D    MT
3  NaN           0   Bennett (R-UT)     Robert  S231   Bennett     R    UT
4  NaN           0     Biden (D-DE)     Joseph  S010     Biden     D    DE
5  NaN           0  Bingaman (D-NM)       Jeff  S167  Bingaman     D    NM
  bill_number     display_name first_name    id last_name party state
1           0   Abraham (R-MI)    Spencer  S238   Abraham     R    MI
2           0     Akaka (D-HI)     Daniel  S213     Akaka     D    HI
3           0  Ashcroft (R-MO)       John  S239  Ashcroft     R    MO
4           0    Baucus (D-MT)        Max  S127    Baucus     D    MT
5           0   Bennett (R-UT)     Robert  S231   Bennett     R    UT
  bill_number     display_name first_name    id last_name party state
1           0     Akaka (D-HI)     Daniel  S213     Akaka     D    HI
2           0    Baucus (D-MT)        Max  S127    Baucus     D    MT
3           0     Biden (D-DE)     Joseph  S010     Biden     D    DE
4           0  Bingaman (D-NM)       Jeff  S167  Bingaman     D    NM
5           0     Boxer (D-CA)    Barbara  S223     Boxer     D    CA
  bill_number     display_name first_name    id last_name party state
1           0   Abraham (R-MI)    Spencer  S238   Abraham     R    MI
2           0     Akaka (D-HI)     Daniel  S213     Akaka     D    HI
3           0    Allard (R-CO)      Wayne  S250    Allard     R    CO
4           0  Ashcroft (R-MO)       John  S239  Ashcroft     R    MO
5           0    Baucus (D-MT)        Max  S127    Baucus     D    MT
  bill_number     display_name first_name    id last_name party state
1           0     Akaka (D-HI)     Daniel  S213     Akaka     D    HI
2           0    Baucus (D-MT)        Max  S127    Baucus     D    MT
3           0   Bennett (R-UT)     Robert  S231   Bennett     R    UT
4           0     Biden (D-DE)     Joseph  S010     Biden     D    DE
5           0  Bingaman (D-NM)       Jeff  S167  Bingaman     D    NM
     0 bill_number     display_name first_name    id last_name party state
1  NaN           0   Abraham (R-MI)    Spencer  S238   Abraham     R    MI
2  NaN           0     Akaka (D-HI)     Daniel  S213     Akaka     D    HI
3  NaN           0    Allard (R-CO)      Wayne  S250    Allard     R    CO
4  NaN           0  Ashcroft (R-MO)       John  S239  Ashcroft     R    MO
5  NaN           0    Baucus (D-MT)        Max  S127    Baucus     D    MT
  bill_number     display_name   first_name    id last_name party state
1           0   Abraham (R-MI)      Spencer  S238   Abraham     R    MI
2           0    Allard (R-CO)        Wayne  S250    Allard     R    CO
3           0  Ashcroft (R-MO)         John  S239  Ashcroft     R    MO
4           0   Bennett (R-UT)       Robert  S231   Bennett     R    UT
5           0      Bond (R-MO)  Christopher  S200      Bond     R    MO
     0 bill_number   display_name first_name    id last_name party state
1  NaN           0   Akaka (D-HI)     Daniel  S213     Akaka     D    HI
2  NaN           0  Allard (R-CO)      Wayne  S250    Allard     R    CO
3  NaN           0   Allen (R-VA)     George  S274     Allen     R    VA
4  NaN           0  Baucus (D-MT)        Max  S127    Baucus     D    MT
5  NaN           0    Bayh (D-IN)       Evan  S264      Bayh     D    IN
     0 bill_number    display_name first_name    id last_name party state
1  NaN           0   Allard (R-CO)      Wayne  S250    Allard     R    CO
2  NaN           0   Baucus (D-MT)        Max  S127    Baucus     D    MT
3  NaN           0     Bayh (D-IN)       Evan  S264      Bayh     D    IN
4  NaN           0  Bennett (R-UT)     Robert  S231   Bennett     R    UT
5  NaN           0    Biden (D-DE)     Joseph  S010     Biden     D    DE
     0 bill_number      display_name   first_name    id  last_name party state
1  NaN           0  Alexander (R-TN)        Lamar  S289  Alexander     R    TN
2  NaN           0     Allard (R-CO)        Wayne  S250     Allard     R    CO
3  NaN           0      Allen (R-VA)       George  S274      Allen     R    VA
4  NaN           0    Bennett (R-UT)       Robert  S231    Bennett     R    UT
5  NaN           0       Bond (R-MO)  Christopher  S200       Bond     R    MO
  bill_number      display_name   first_name    id  last_name party state
1           0  Alexander (R-TN)        Lamar  S289  Alexander     R    TN
2           0     Allard (R-CO)           A.  S250     Allard     R    CO
3           0      Allen (R-VA)       George  S274      Allen     R    VA
4           0    Bennett (R-UT)       Robert  S231    Bennett     R    UT
5           0       Bond (R-MO)  Christopher  S200       Bond     R    MO
     0 bill_number      display_name first_name    id  last_name party state
1  NaN           0      Boxer (D-CA)    Barbara  S223      Boxer     D    CA
2  NaN           1  Alexander (R-TN)      Lamar  S289  Alexander     R    TN
3  NaN           1     Allard (R-CO)         A.  S250     Allard     R    CO
4  NaN           1      Allen (R-VA)     George  S274      Allen     R    VA
5  NaN           1     Baucus (D-MT)        Max  S127     Baucus     D    MT
  bill_number      display_name first_name    id  last_name party state
1           0      Akaka (D-HI)     Daniel  S213      Akaka     D    HI
2           0  Alexander (R-TN)      Lamar  S289  Alexander     R    TN
3           0     Allard (R-CO)         A.  S250     Allard     R    CO
4           0      Allen (R-VA)     George  S274      Allen     R    VA
5           0     Baucus (D-MT)        Max  S127     Baucus     D    MT
  bill_number    display_name first_name    id last_name party state
1           0    Akaka (D-HI)     Daniel  S213     Akaka     D    HI
2           0   Allard (R-CO)         A.  S250    Allard     R    CO
3           0   Baucus (D-MT)        Max  S127    Baucus     D    MT
4           0     Bayh (D-IN)       Evan  S264      Bayh     D    IN
5           0  Bennett (R-UT)     Robert  S231   Bennett     R    UT
     0 bill_number      display_name first_name    id  last_name party state
1  NaN           0      Akaka (D-HI)     Daniel  S213      Akaka     D    HI
2  NaN           0  Alexander (R-TN)      Lamar  S289  Alexander     R    TN
3  NaN           0     Allard (R-CO)         A.  S250     Allard     R    CO
4  NaN           0   Barrasso (R-WY)       John  S317   Barrasso     R    WY
5  NaN           0     Baucus (D-MT)        Max  S127     Baucus     D    MT
  bill_number     display_name first_name    id last_name party state
1           0     Akaka (D-HI)     Daniel  S213     Akaka     D    HI
2           0  Barrasso (R-WY)       John  S317  Barrasso     R    WY
3           0    Baucus (D-MT)        Max  S127    Baucus     D    MT
4           0      Bayh (D-IN)       Evan  S264      Bayh     D    IN
5           0    Begich (D-AK)       Mark  S319    Begich     D    AK
  bill_number      display_name first_name    id  last_name party state
1           0      Akaka (D-HI)     Daniel  S213      Akaka     D    HI
2           0  Alexander (R-TN)      Lamar  S289  Alexander     R    TN
3           0   Barrasso (R-WY)       John  S317   Barrasso     R    WY
4           0     Baucus (D-MT)        Max  S127     Baucus     D    MT
5           0       Bayh (D-IN)       Evan  S264       Bayh     D    IN
  bill_number      display_name first_name    id  last_name party state
1           0      Akaka (D-HI)     Daniel  S213      Akaka     D    HI
2           0  Alexander (R-TN)      Lamar  S289  Alexander     R    TN
3           0     Ayotte (R-NH)      Kelly  S340     Ayotte     R    NH
4           0   Barrasso (R-WY)       John  S317   Barrasso     R    WY
5           0     Baucus (D-MT)        Max  S127     Baucus     D    MT
  bill_number      display_name first_name    id  last_name party state
1           0      Akaka (D-HI)     Daniel  S213      Akaka     D    HI
2           0  Alexander (R-TN)      Lamar  S289  Alexander     R    TN
3           0     Ayotte (R-NH)      Kelly  S340     Ayotte     R    NH
4           0   Barrasso (R-WY)       John  S317   Barrasso     R    WY
5           0     Baucus (D-MT)        Max  S127     Baucus     D    MT
  bill_number      display_name first_name    id  last_name party state
1           0  Alexander (R-TN)      Lamar  S289  Alexander     R    TN
2           0     Ayotte (R-NH)      Kelly  S340     Ayotte     R    NH
3           0    Baldwin (D-WI)      Tammy  S354    Baldwin     D    WI
4           0   Barrasso (R-WY)       John  S317   Barrasso     R    WY
5           0     Baucus (D-MT)        Max  S127     Baucus     D    MT

In [64]:
for i in range(1989, 2014):
    if 0 in vote_yes[i].columns:
        vote_yes[i].drop(0, )

In [67]:
for year in vote_yes: 
    vote_yes[year].to_csv(str(year) + '_yes_votes.csv')

In [71]:
vote_data_year[1989] = [bill['Yea'] for bill in vote_data_year[1989]]
#list of lists, each list is group of people who voted for the same bill

In [104]:
df = df.dropna()

In [5]:
vote_data_year = {}
vote_data_by_year = json.loads(open("senatevotedata.json").read())
#vote_data = pd.read_
vote_yes = {}
for year in range(1994, 1995):
    vote_data_year[year] = list(pd.DataFrame(vote_data_by_year["year"][str(year)])['votes'])

In [24]:
year = 1994
vote_data_year[year] = list(pd.DataFrame(vote_data_by_year["year"][str(year)])['votes'])
vote_data_year[year] = [bill['Yea'] for bill in vote_data_year[year]]

#list of lists, each list is group of people who voted for the same bill
df = pd.Series()
bill_number = 0
for bill in vote_data_year[year]:
    for person in bill:
        df = pd.concat([df,pd.Series(person).append(pd.Series([bill_number], index = ['bill_number']))], axis = 1)
    bill_number += 1
print df.head()
'''
df = df.transpose()
vote_yes[year] = df    
vote_yes[year] = vote_yes[year].dropna()
'''

               0             1              0               0             0  \
0            NaN           NaN            NaN             NaN           NaN
bill_number  NaN             0              0               0             0
display_name NaN  Akaka (D-HI)  Baucus (D-MT)  Bennett (R-UT)  Biden (D-DE)
first_name   NaN        Daniel            Max          Robert        Joseph
id           NaN          S213           S127            S231          S010

                            0            0             0             0  \
0                         NaN          NaN           NaN           NaN
bill_number                 0            0             0             0
display_name  Bingaman (D-NM)  Bond (R-MO)  Boren (D-OK)  Boxer (D-CA)
first_name               Jeff  Christopher         David       Barbara
id                       S167         S200          S128          S223

                           0       ...                         0            0  \
0                        NaN       ...                       NaN          NaN
bill_number                0       ...                       328          328
display_name  Bradley (D-NJ)       ...        Rockefeller (D-WV)  Roth (R-DE)
first_name              Bill       ...                      John      William
id                      S132       ...                      S176         S083

                            0              0             0               0  \
0                         NaN            NaN           NaN             NaN
bill_number               328            328           328             328
display_name  Sarbanes (D-MD)  Sasser (D-TN)  Simon (D-IL)  Simpson (R-WY)
first_name               Paul            Jim          Paul            Alan
id                       S106           S117          S175            S142

                           0              0              0               0
0                        NaN            NaN            NaN             NaN
bill_number              328            328            328             328
display_name  Specter (R-PA)  Wallop (R-WY)  Warner (R-VA)  Wofford (D-PA)
first_name             Arlen        Malcolm           John          Harris
id                      S161           S119           S143            S219

[5 rows x 21660 columns]

'\ndf = df.transpose()\nvote_yes[year] = df    \nvote_yes[year] = vote_yes[year].dropna()\n'

In [45]:
df = df.transpose()
df = df.ix[1:]
df.head()

  bill_number     display_name first_name    id last_name party state
1           0     Akaka (D-HI)     Daniel  S213     Akaka     D    HI
0           0    Baucus (D-MT)        Max  S127    Baucus     D    MT
0           0     Biden (D-DE)     Joseph  S010     Biden     D    DE
0           0  Bingaman (D-NM)       Jeff  S167  Bingaman     D    NM
0           0     Boxer (D-CA)    Barbara  S223     Boxer     D    CA

In [44]:
vote_yes[year] = 
vote_yes[year].head()

,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
display_name,NaN,Akaka (D-HI),Baucus (D-MT),Biden (D-DE),Bingaman (D-NM),Boxer (D-CA),Bradley (D-NJ),Breaux (D-LA),Bryan (D-NV),Bumpers (D-AR),...,Burns (R-MT),Byrd (D-WV),Cochran (R-MS),Conrad (D-ND),Coverdell (R-GA),D'Amato (R-NY),Daschle (D-SD),DeWine (R-OH),Dodd (D-CT),Domenici (R-NM)
first_name,NaN,Daniel,Max,Joseph,Jeff,Barbara,Bill,John,Richard,Dale,...,Conrad,Robert,Thad,Kent,Paul,Alfonse,Thomas,Mike,Christopher,Pete
id,NaN,S213,S127,S010,S167,S223,S132,S179,S206,S014,...,S211,S017,S136,S201,S228,S147,S185,S240,S150,S027
last_name,NaN,Akaka,Baucus,Biden,Bingaman,Boxer,Bradley,Breaux,Bryan,Bumpers,...,Burns,Byrd,Cochran,Conrad,Coverdell,D'Amato,Daschle,DeWine,Dodd,Domenici
party,NaN,D,D,D,D,D,D,D,D,D,...,R,D,R,D,R,R,D,R,D,R

In [39]:
df

,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bill_number,NaN,0,0,0,0,0,0,0,0,0,...,328,328,328,328,328,328,328,328,328,328
display_name,NaN,Akaka (D-HI),Baucus (D-MT),Bennett (R-UT),Biden (D-DE),Bingaman (D-NM),Bond (R-MO),Boren (D-OK),Boxer (D-CA),Bradley (D-NJ),...,Rockefeller (D-WV),Roth (R-DE),Sarbanes (D-MD),Sasser (D-TN),Simon (D-IL),Simpson (R-WY),Specter (R-PA),Wallop (R-WY),Warner (R-VA),Wofford (D-PA)
first_name,NaN,Daniel,Max,Robert,Joseph,Jeff,Christopher,David,Barbara,Bill,...,John,William,Paul,Jim,Paul,Alan,Arlen,Malcolm,John,Harris
id,NaN,S213,S127,S231,S010,S167,S200,S128,S223,S132,...,S176,S083,S106,S117,S175,S142,S161,S119,S143,S219
last_name,NaN,Akaka,Baucus,Bennett,Biden,Bingaman,Bond,Boren,Boxer,Bradley,...,Rockefeller,Roth,Sarbanes,Sasser,Simon,Simpson,Specter,Wallop,Warner,Wofford
party,NaN,D,D,R,D,D,R,D,D,D,...,D,R,D,D,D,R,R,R,R,D
state,NaN,HI,MT,UT,DE,NM,MO,OK,CA,NJ,...,WV,DE,MD,TN,IL,WY,PA,WY,VA,PA